// <auto-generated />
namespace Inspotivity.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class tookoutenum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tookoutenum));
        
        string IMigrationMetadata.Id
        {
            get { return "202110201337039_took-out-enum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
